apiVersion: v1
kind: PersistentVolume
metadata:
  name: todo-staging-pv
spec:
  storageClassName: todo-staging-storage
  capacity:
    storage: 1Gi 
  volumeMode: Filesystem 
  accessModes:
  - ReadWriteOnce
  local:
    path: /tmp/kube
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - k3d-k3s-default-agent-0