apiVersion: batch/v1
kind: CronJob
metadata:
  name: todo-backup-job
spec:
  schedule: "0 * * * *"
  concurrencyPolicy: "Forbid"
  successfulJobsHistoryLimit: 0
  failedJobsHistoryLimit: 0
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: todo-backup-job
            image: JOB-BACKUP
            imagePullPolicy: Always
            envFrom:
            - configMapRef:
                name: project-config
            env:
            - name: URL
              value: "postgres://admin:123456@postgres-service:5432/postgres"
            volumeMounts:
                - name: backup-volume
                  mountPath: /backup
          volumes:
            - name: backup-volume
              persistentVolumeClaim:
                claimName: todo-backup-claim
          restartPolicy: OnFailure