apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: todo-storage-claim-production
spec:
  volumeName: todo-production-pv
  storageClassName: todo-production-storage
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: todo-backup-claim
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi